import { NextResponse } from 'next/server'
import prisma from '@/lib/db'
import { put } from '@vercel/blob'
import { analyzeWithGrok } from '@/lib/grok'
import { resizeImage } from '@/lib/image-utils'

export async function POST(req: Request) {
  try {
    const formData = await req.formData()
    const file = formData.get('photo') as File
    const checkInId = formData.get('checkInId') as string
    const patientId = formData.get('patientId') as string
    const message = formData.get('message') as string

    if (!file || !checkInId || !patientId) {
      return NextResponse.json(
        { error: 'Photo, check-in ID, and patient ID are required' },
        { status: 400 }
      )
    }

    const bytes = await file.arrayBuffer()
    let buffer = Buffer.from(bytes)

    const filename = `${Date.now()}-${file.name}`
    const blob = await put(`uploads/${filename}`, buffer, {
      access: 'public',
      contentType: file.type,
    })
    const imageUrl = blob.url

    const base64Image = await resizeImage(buffer, file.type)

    const checkIn = await prisma.recoveryCheckIn.findUnique({
      where: { id: checkInId },
      include: { treatment: { select: { type: true } } },
    })

    const grokResult = await analyzeWithGrok(
      base64Image,
      file.type,
      checkIn?.treatment?.type,
      checkIn?.dayNumber
    )

    const features = grokResult.clinicalFeatures

    const photo = await prisma.patientPhoto.create({
      data: {
        patientId,
        checkInId,
        imageUrl: imageUrl,
        metadata: JSON.stringify({
          originalName: file.name,
          size: file.size,
          type: file.type,
          grokLabels: grokResult.labels,
        }),
      },
    })

    const aiAnalysis = await prisma.aIAnalysis.create({
      data: {
        photoId: photo.id,
        checkInId,
        swellingScore: features.edema,
        bruisingScore: features.ecchymosis,
        rednessScore: features.erythema,
        asymmetryScore: features.asymmetry,
        noduleScore: features.nodules,
        vascularityScore: features.vascularity,
        overallScore: (features.edema + features.ecchymosis + features.erythema + features.asymmetry) / 4,
        confidenceScore: 0.8 + Math.random() * 0.15,
        riskLevel: grokResult.riskLevel,
        status: grokResult.riskLevel === 'RED' || grokResult.riskLevel === 'ORANGE' ? 'UNDER_REVIEW' : 'COMPLETED',
        clinicalFeatures: JSON.stringify(features),
        findings: JSON.stringify(grokResult.findings),
        recommendations: JSON.stringify(grokResult.recommendations),
        clinicalSummary: grokResult.clinicalSummary,
        recommendedAction: grokResult.recommendedAction,
        rawResponse: JSON.stringify({ grokResult }),
      },
    })

    const shouldEscalate = grokResult.riskLevel === 'RED' || grokResult.riskLevel === 'ORANGE'
    const newStatus = shouldEscalate ? 'ESCALATED' : 'COMPLETED'

    await prisma.recoveryCheckIn.update({
      where: { id: checkInId },
      data: {
        status: newStatus,
        patientMessage: message || undefined,
        aiResponse: grokResult.aiResponse,
        riskLevel: grokResult.riskLevel,
        completedDate: new Date(),
      },
    })

    let nextCheckIn = null
    let nextCheckInHours: number | null = null

    if (grokResult.riskLevel === 'YELLOW') {
      nextCheckInHours = 24
    } else if (grokResult.riskLevel === 'ORANGE') {
      nextCheckInHours = 4
    } else if (grokResult.riskLevel === 'RED') {
      nextCheckInHours = 1
    }

    if (nextCheckInHours) {
      const currentCheckIn = await prisma.recoveryCheckIn.findUnique({
        where: { id: checkInId },
        select: { treatmentId: true, patientId: true, dayNumber: true },
      })

      if (currentCheckIn) {
        const nextDate = new Date()
        nextDate.setHours(nextDate.getHours() + nextCheckInHours)

        nextCheckIn = await prisma.recoveryCheckIn.create({
          data: {
            treatmentId: currentCheckIn.treatmentId,
            patientId: currentCheckIn.patientId,
            dayNumber: currentCheckIn.dayNumber + 1,
            scheduledDate: nextDate,
            status: 'PENDING',
            riskLevel: 'GREEN',
          },
        })
      }
    }

    return NextResponse.json({
      photo,
      analysis: aiAnalysis,
      riskLevel: grokResult.riskLevel,
      findings: grokResult.findings,
      recommendations: grokResult.recommendations,
      aiResponse: grokResult.aiResponse,
      clinicalSummary: grokResult.clinicalSummary,
      recommendedAction: grokResult.recommendedAction,
      nextCheckIn,
      shouldEscalate,
      visionLabels: grokResult.labels,
      disclaimer: 'This analysis is generated by AI clinical decision support system and should not replace professional medical advice. Always consult your healthcare provider for clinical decisions.',
    }, { status: 201 })
  } catch (error) {
    console.error('Error uploading photo:', error)
    const message = error instanceof Error ? error.message : 'Unknown error'
    console.error('Error details:', message)
    return NextResponse.json({ error: 'Internal server error: ' + message }, { status: 500 })
  }
}
